//
//  NSString+FontAwesome.h
//
//  Copyright (c) 2012 Alex Usbergo. All rights reserved.
//
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//

#import <Foundation/Foundation.h>


//
//typedef NS_ENUM(NSInteger,FMIconFont){
//    FMIconHomePage,             /**< 00 首页模块信息*/
//    FMIconFond,                 /**< 01 发现模块信息*/
//    FMIconTakeCamera,           /**< 02 拍照模块信息*/
//    FMIconPersonlMsg,           /**< 03 个人消息模块信息*/
//    FMIconPersonalInfo,         /**< 04 个人模块信息*/
//    FMIconPersonalDNA,          /**< 05 个人DNA*/
//    FMIconAttention,            /**< 06 关注（心型，实心）*/
//    FMIconLocation,             /**< 07 定位操作(下面没有信息)*/
//    FMIconSkim,                 /**< 08 浏览(眼睛小图标)*/
//    FMIconComment,              /**< 09 评论*/
//    FMIconNULL,                 /**< 0A 空信息，没有任何数据内容*/
//    FMIconOrder,                /**< 0B 订单*/
//    FMIconLock,                 /**< 0C 锁（密码信息）*/
//    FMIconVerifyCode,           /**< 0D 验证码*/
//    FMIconLeftReturn,           /**< 0E 向左返回*/
//    FMIconCloseEdit,            /**< 0F 关闭编辑 */
//    FMIconSelected,             /**< 10 对号选择（没有圆圈，仅有对号） */
//    FMIconUpDownSelected,       /**< 11 上下信息选择 */
//    FMIconAdd,                  /**< 12 圆形添加，即加号*/
//    FMIconRightLineArrow,       /**< 13 向右的横向箭头（横线+向右箭头）*/
//    FMIconSelectedBorder,       /**< 14 对号选择（有圆圈，有对号） */
//    FMIconChat,                 /**< 15 聊天操作 */
//    FMIconLowerArrow,           /**< 16 向下箭头*/
//    FMIconRightArrow,           /**< 17 向右箭头*/
//    FMIconRightReturn,          /**< 18 向右操作*/
//    FMIconSubtract,             /**< 19 圆形见好，即减号*/
//    FMIconStarAttention,        /**< 1A 关注（默认状态,星星空心）*/
//    FMIconEidt,                 /**< 1B 编辑（铅笔形状）*/
//    FMIconStarSolidAttention,   /**< 1C 关注（高亮状态,星星实心）*/
//    FMIconDelete,               /**< 1D 删除 */
//    FMIconAttentionSolidHeart,  /**< 1E 关注（心型，空心）*/
//    FMIconShare,                /**< 1F 分享 */
//    FMIconAddMedia,             /**< 20 添加多媒体信息 */
//    FMIconSmileExpression,      /**< 21 微笑表情 */
//    FMIconVoice,                /**< 22 声音媒体 */
//    FMIconGenderMale,           /**< 23 性别男 */
//    FMIconGenderFemale,         /**< 24 性别女 */
//    FMIconUserSendInfor,        /**< 25 发布信息 */
//    FMIconCamera,               /**< 26 拍照*/
//    FMIconPraiseBorder,         /**< 27 赞（空心的，只有边框手势）*/
//    FMIconPraise,               /**< 28 赞（实心的，）*/
//    FMIconSelectedAct,          /**< 29 选则沙龙*/
//    FMIconPic,                  /**< 2A 图片设置*/
//    FMIconSetting,              /**< 2B 设置*/
//    FMIconPhoneNumber,          /**< 2C 手机号*/
//    FMIconRMBIcon,              /**< 2D 人民币*/
//};

typedef NS_ENUM(NSInteger,FMIconFont){
    FMIconNULL = 0,
    FMIconFontF000 = 0,
    FMIconFontF001 = 1,
    FMIconFontF002,
    FMIconFontF003,
    FMIconFontF004,
    FMIconFontF005,
    FMIconFontF006,
    FMIconFontF007,
    FMIconFontF008,
    FMIconFontF009,
    FMIconFontF00A,
    FMIconFontF00B,
    FMIconFontF00C,
    FMIconFontF00D,
    FMIconFontF00E,
    FMIconFontF010,
    FMIconFontF011,
    FMIconFontF012,
    FMIconFontF013,
    FMIconFontF014,
    FMIconFontF015,
    FMIconFontF016,
    FMIconFontF017,
    FMIconFontF018,
    FMIconFontF019,
    FMIconFontF01A,
    FMIconFontF01B,
    FMIconFontF01C,
    FMIconFontF01D,
    FMIconFontF01E,
    FMIconFontF021,
    FMIconFontF022,
    FMIconFontF023,
    FMIconFontF024,
    FMIconFontF025,
    FMIconFontF026,
    FMIconFontF027,
    FMIconFontF028,
    FMIconFontF029,
    FMIconFontF02A,
    FMIconFontF02B,
    FMIconFontF02C,
    FMIconFontF02D,
    FMIconFontF02E,
    FMIconFontF02F,
    FMIconFontF030,
    FMIconFontF031,
    FMIconFontF032,
    FMIconFontF033,
    FMIconFontF034,
    FMIconFontF035,
    FMIconFontF036,
    FMIconFontF037,
    FMIconFontF038,
    FMIconFontF039,
    FMIconFontF03A,
    FMIconFontF03B,
    FMIconFontF03C,
    FMIconFontF03D,
    FMIconFontF03E,
    FMIconFontF040,
    FMIconFontF041,
    FMIconFontF042,
    FMIconFontF043,
    FMIconFontF044,
    FMIconFontF045,
    FMIconFontF046,
    FMIconFontF047,
    FMIconFontF048,
    FMIconFontF049,
    FMIconFontF04A,
    FMIconFontF04B,
    FMIconFontF04C,
    FMIconFontF04D,
    FMIconFontF04E,
    FMIconFontF050,
    FMIconFontF051,
    FMIconFontF052,
    FMIconFontF053,
    FMIconFontF054,
    FMIconFontF055,
    FMIconFontF056,
    FMIconFontF057,
    FMIconFontF058,
    FMIconFontF059,
    FMIconFontF05A,
    FMIconFontF05B,
    FMIconFontF05C,
    FMIconFontF05D,
    FMIconFontF05E,
    FMIconFontF060,
    FMIconFontF061,
    FMIconFontF062,
    FMIconFontF063,
    FMIconFontF064,
    FMIconFontF065,
    FMIconFontF066,
    FMIconFontF067,
    FMIconFontF068,
    FMIconFontF069,
    FMIconFontF06A,
    FMIconFontF06B,
    FMIconFontF06C,
    FMIconFontF06D,
    FMIconFontF06E,
    FMIconFontF070,
    FMIconFontF071,
    FMIconFontF072,
    FMIconFontF073,
    FMIconFontF074,
    FMIconFontF075,
    FMIconFontF076,
    FMIconFontF077,
    FMIconFontF078,
    FMIconFontF079,
    FMIconFontF07A,
    FMIconFontF07B,
    FMIconFontF07C,
    FMIconFontF07D,
    FMIconFontF07E,
    FMIconFontF080,
    FMIconFontF081,
    FMIconFontF082,
    FMIconFontF083,
    FMIconFontF084,
    FMIconFontF085,
    FMIconFontF086,
    FMIconFontF087,
    FMIconFontF088,
    FMIconFontF089,
    FMIconFontF08A,
    FMIconFontF08B,
    FMIconFontF08C,
    FMIconFontF08D,
    FMIconFontF08E,
    FMIconFontF090,
    FMIconFontF091,
    FMIconFontF092,
    FMIconFontF093,
    FMIconFontF094,
    FMIconFontF095,
    FMIconFontF096,
    FMIconFontF097,
    FMIconFontF098,
    FMIconFontF099,
    FMIconFontF09A,
    FMIconFontF09B,
    FMIconFontF09C,
    FMIconFontF09D,
    FMIconFontF09E,
    FMIconFontF0A0,
    FMIconFontF0A1,
    FMIconFontF0A2,
    FMIconFontF0A3,
    FMIconFontF0A4,
    FMIconFontF0A5,
    FMIconFontF0A6,
    FMIconFontF0A7,
    FMIconFontF0A8,
    FMIconFontF0A9,
    FMIconFontF0AA,
    FMIconFontF0AB,
    FMIconFontF0AC,
    FMIconFontF0AD,
    FMIconFontF0AE,
    FMIconFontF0B0,
    FMIconFontF0B1,
    FMIconFontF0B2,
    FMIconFontF0B3,
    FMIconFontF0B4,
    FMIconFontF0B5,
    FMIconFontF0B6,
    FMIconFontF0B7,
    FMIconFontF0B8,
    FMIconFontF0B9,
    FMIconFontF0BA,
    FMIconFontF0BB,
    FMIconFontF0BC,
    FMIconFontF0BD,
    FMIconFontF0BE,
    FMIconFontF0C0,
    FMIconFontF0C1,
    FMIconFontF0C2,
    FMIconFontF0C3,
    FMIconFontF0C4,
    FMIconFontF0C5,
    FMIconFontF0C6,
    FMIconFontF0C7,
    FMIconFontF0C8,
    FMIconFontF0C9,
    FMIconFontF0CA,
    FMIconFontF0CB,
    FMIconFontF0CC,
    FMIconFontF0CD,
    FMIconFontF0CE,
    FMIconFontF0D0,
    FMIconFontF0D1,
    FMIconFontF0D2,
    FMIconFontF0D3,
    FMIconFontF0D4,
    FMIconFontF0D5,
    FMIconFontF0D6,
    FMIconFontF0D7,
    FMIconFontF0D8,
    FMIconFontF0D9,
    FMIconFontF0DA,
    FMIconFontF0DB,
    FMIconFontF0DC,
    FMIconFontF0DD,
    FMIconFontF0DE,
    FMIconFontF0E0,
    FMIconFontF0E1,
    FMIconFontF0E2,
    FMIconFontF0E3,
    FMIconFontF0E4,
    FMIconFontF0E5,
    FMIconFontF0E6,
    FMIconFontF0E7,
    FMIconFontF0E8,
    FMIconFontF0E9,
    FMIconFontF0EA,
    FMIconFontF0EB,
    FMIconFontF0EC,
    FMIconFontF0ED,
    FMIconFontF0EE,
    FMIconFontF0F0,
    FMIconFontF0F1,
    FMIconFontF0F2,
    FMIconFontF0F3,
    FMIconFontF0F4,
    FMIconFontF0F5,
    FMIconFontF0F6,
    FMIconFontF0F7,
    FMIconFontF0F8,
    FMIconFontF0F9,
    FMIconFontF0FA,
    FMIconFontF0FB,
    FMIconFontF0FC,
    FMIconFontF0FD,
    FMIconFontF0FE,
    
    
    FMIconFontF100,
    FMIconFontF101,
    FMIconFontF102,
    FMIconFontF103,
    FMIconFontF104,
    FMIconFontF105,
    FMIconFontF106,
    FMIconFontF107,
    FMIconFontF108,
    FMIconFontF109,
    FMIconFontF10A,
    FMIconFontF10B,
    FMIconFontF10C,
    FMIconFontF10D,
    FMIconFontF10E,
    FMIconFontF110,
    FMIconFontF111,
    FMIconFontF112,
    FMIconFontF113,
    FMIconFontF114,
    FMIconFontF115,
    FMIconFontF116,
    FMIconFontF117,
    FMIconFontF118,
    FMIconFontF119,
    FMIconFontF11A,
    FMIconFontF11B,
    FMIconFontF11C,
    FMIconFontF11D,
    FMIconFontF11E,
    FMIconFontF121,
    FMIconFontF122,
    FMIconFontF123,
    FMIconFontF124,
    FMIconFontF125,
    FMIconFontF126,
    FMIconFontF127,
    FMIconFontF128,
    FMIconFontF129,
    FMIconFontF12A,
    FMIconFontF12B,
    FMIconFontF12C,
    FMIconFontF12D,
    FMIconFontF12E,
    FMIconFontF12F,
    FMIconFontF130,
    FMIconFontF131,
    FMIconFontF132,
    FMIconFontF133,
    FMIconFontF134,
    FMIconFontF135,
    FMIconFontF136,
    FMIconFontF137,
    FMIconFontF138,
    FMIconFontF139,
    FMIconFontF13A,
    FMIconFontF13B,
    FMIconFontF13C,
    FMIconFontF13D,
    FMIconFontF13E,
    FMIconFontF140,
    FMIconFontF141,
    FMIconFontF142,
    FMIconFontF143,
    FMIconFontF144,
    FMIconFontF145,
    FMIconFontF146,
    FMIconFontF147,
    FMIconFontF148,
    FMIconFontF149,
    FMIconFontF14A,
    FMIconFontF14B,
    FMIconFontF14C,
    FMIconFontF14D,
    FMIconFontF14E,
    FMIconFontF150,
    FMIconFontF151,
    FMIconFontF152,
    FMIconFontF153,
    FMIconFontF154,
    FMIconFontF155,
    FMIconFontF156,
    FMIconFontF157,
    FMIconFontF158,
    FMIconFontF159,
    FMIconFontF15A,
    FMIconFontF15B,
    FMIconFontF15C,
    FMIconFontF15D,
    FMIconFontF15E,
    FMIconFontF160,
    FMIconFontF161,
    FMIconFontF162,
    FMIconFontF163,
    FMIconFontF164,
    FMIconFontF165,
    FMIconFontF166,
    FMIconFontF167,
    FMIconFontF168,
    FMIconFontF169,
    FMIconFontF16A,
    FMIconFontF16B,
    FMIconFontF16C,
    FMIconFontF16D,
    FMIconFontF16E,
    FMIconFontF170,
    FMIconFontF171,
    FMIconFontF172,
    FMIconFontF173,
    FMIconFontF174,
    FMIconFontF175,
    FMIconFontF176,
    FMIconFontF177,
    FMIconFontF178,
    FMIconFontF179,
    FMIconFontF17A,
    FMIconFontF17B,
    FMIconFontF17C,
    FMIconFontF17D,
    FMIconFontF17E,
    FMIconFontF180,
    FMIconFontF181,
    FMIconFontF182,
    FMIconFontF183,
    FMIconFontF184,
    FMIconFontF185,
    FMIconFontF186,
    FMIconFontF187,
    FMIconFontF188,
    FMIconFontF189,
    FMIconFontF18A,
    FMIconFontF18B,
    FMIconFontF18C,
    FMIconFontF18D,
    FMIconFontF18E,
    FMIconFontF190,
    FMIconFontF191,
    FMIconFontF192,
    FMIconFontF193,
    FMIconFontF194,
    FMIconFontF195,
    FMIconFontF196,
    FMIconFontF197,
    FMIconFontF198,
    FMIconFontF199,
    FMIconFontF19A,
    FMIconFontF19B,
    FMIconFontF19C,
    FMIconFontF19D,
    FMIconFontF19E,
    FMIconFontF1A0,
    FMIconFontF1A1,
    FMIconFontF1A2,
    FMIconFontF1A3,
    FMIconFontF1A4,
    FMIconFontF1A5,
    FMIconFontF1A6,
    FMIconFontF1A7,
    FMIconFontF1A8,
    FMIconFontF1A9,
    FMIconFontF1AA,
    FMIconFontF1AB,
    FMIconFontF1AC,
    FMIconFontF1AD,
    FMIconFontF1AE,
    FMIconFontF1B0,
    FMIconFontF1B1,
    FMIconFontF1B2,
    FMIconFontF1B3,
    FMIconFontF1B4,
    FMIconFontF1B5,
    FMIconFontF1B6,
    FMIconFontF1B7,
    FMIconFontF1B8,
    FMIconFontF1B9,
    FMIconFontF1BA,
    FMIconFontF1BB,
    FMIconFontF1BC,
    FMIconFontF1BD,
    FMIconFontF1BE,
    FMIconFontF1C0,
    FMIconFontF1C1,
    FMIconFontF1C2,
    FMIconFontF1C3,
    FMIconFontF1C4,
    FMIconFontF1C5,
    FMIconFontF1C6,
    FMIconFontF1C7,
    FMIconFontF1C8,
    FMIconFontF1C9,
    FMIconFontF1CA,
    FMIconFontF1CB,
    FMIconFontF1CC,
    FMIconFontF1CD,
    FMIconFontF1CE,
    FMIconFontF1D0,
    FMIconFontF1D1,
    FMIconFontF1D2,
    FMIconFontF1D3,
    FMIconFontF1D4,
    FMIconFontF1D5,
    FMIconFontF1D6,
    FMIconFontF1D7,
    FMIconFontF1D8,
    FMIconFontF1D9,
    FMIconFontF1DA,
    FMIconFontF1DB,
    FMIconFontF1DC,
    FMIconFontF1DD,
    FMIconFontF1DE,
    FMIconFontF1E0,
    FMIconFontF1E1,
    FMIconFontF1E2,
    FMIconFontF1E3,
    FMIconFontF1E4,
    FMIconFontF1E5,
    FMIconFontF1E6,
    FMIconFontF1E7,
    FMIconFontF1E8,
    FMIconFontF1E9,
    FMIconFontF1EA,
    FMIconFontF1EB,
    FMIconFontF1EC,
    FMIconFontF1ED,
    FMIconFontF1EE,
    FMIconFontF1F0,
    FMIconFontF1F1,
    FMIconFontF1F2,
    FMIconFontF1F3,
    FMIconFontF1F4,
    FMIconFontF1F5,
    FMIconFontF1F6,
    FMIconFontF1F7,
    FMIconFontF1F8,
    FMIconFontF1F9,
    FMIconFontF1FA,
    FMIconFontF1FB,
    FMIconFontF1FC,
    FMIconFontF1FD,
    FMIconFontF1FE,
    FMIconFontF200,
    FMIconFontF201,
    FMIconFontF202,
    FMIconFontF203,
    FMIconFontF204,
    FMIconFontF205,
    FMIconFontF206,
    FMIconFontF207,
    FMIconFontF208,
    FMIconFontF209,
    FMIconFontF20A,
    FMIconFontF20B,
    FMIconFontF20C,
    FMIconFontF20D,
    FMIconFontF20E,
    FMIconFontF210,
    FMIconFontF211,
    FMIconFontF212,
    FMIconFontF213,
    FMIconFontF214,
    FMIconFontF215,
    FMIconFontF216,
    FMIconFontF217,
    FMIconFontF218,
    FMIconFontF219,
    FMIconFontF21A,
    FMIconFontF21B,
    FMIconFontF21C,
    FMIconFontF21D,
    FMIconFontF21E,
    FMIconFontF221,
    FMIconFontF222,
    FMIconFontF223,
    FMIconFontF224,
    FMIconFontF225,
    FMIconFontF226,
    FMIconFontF227,
    FMIconFontF228,
    FMIconFontF229,
    FMIconFontF22A,
    FMIconFontF22B,
    FMIconFontF22C,
    FMIconFontF230,
    FMIconFontF231,
    FMIconFontF232,
    FMIconFontF233,
    FMIconFontF234,
    FMIconFontF235,
    FMIconFontF236,
    FMIconFontF237,
    FMIconFontF238,
    FMIconFontF239,
    FMIconFontF23A,
    FMIconFontF23B,
};

@interface NSString (FontAwesome)

/**
 @abstract Returns the correct enum for a font-awesome icon.
 @discussion The list of identifiers can be found here: http://fortawesome.github.com/Font-Awesome/#all-icons 
 */
+ (FMIconFont)fontAwesomeEnumForIconIdentifier:(NSString*)string;

/**
 @abstract Returns the font-awesome character associated to the icon enum passed as argument 
 */
+ (NSString*)fontAwesomeIconStringForEnum:(FMIconFont)value;

/* 
 @abstract Returns the font-awesome character associated to the font-awesome identifier.
 @discussion The list of identifiers can be found here: http://fortawesome.github.com/Font-Awesome/#all-icons
 */
+ (NSString*)fontAwesomeIconStringForIconIdentifier:(NSString*)identifier;

@end
